spring.application.name=fc-membership
server.forward-headers-strategy=FRAMEWORK

# Server
server.port=${PORT:8080}

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:membershipdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=fcadmin
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# H2 Web Console (visit: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI (visit: http://localhost:8080/swagger-ui.html)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.firstclub=DEBUG